FROM php:7.4-fpm

# Arguments defined in docker-compose.yml
#ARG user
#ARG uid
ARG user=appuser
ARG uid=1001

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip 

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd \
&& docker-php-source delete

# Get latest Composer
#COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer



# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user 

## Install Php Redis Extension
#RUN pecl install -o -f redis \
#    &&  rm -rf /tmp/pear \
#    &&  docker-php-ext-enable redis

# Set working directory
WORKDIR /var/www

USER $user

##RUN docker-compose exec app composer install 
##RUN docker-compose exec app php artisan key:generate
#RUN cd /var/www && composer install && php artisan key:generate
#RUN php artisan key:generate

#COPY . /app
#
#RUN composer install --no-interaction
#CMD php artisan serve --host=0.0.0.0 --port=8000
#RUN /usr/local/bin/composer install
#RUN php artisan key:generate